### ISSUE TITLE
Crash due to permissions issue

### ISSUE THREAD

**Issue by gingerbeardman** [jkwill87/mnamer#175]
I encountered a crash and am filing it here as directed in the crash text:

```
Starting mnamer

Processing Episode "Euphoria (US) - S02E03 - Ruminations - Big and Little Bullies.mp4" (343.07MB)
moving to /mnt/sort/Euphoria - S02E03 - Ruminations Big and Little Bullys.mp4

============================== CRASH REPORT BEGIN ==============================

--------------------------------- environment ----------------------------------

 - date = 2022-01-25
 - platform = Linux-3.10.105-x86_64-with
 - arguments = ['-b', '-r', '/mnt/new', '--episode-directory=/mnt/sort', '--movie-directory=/mnt/sort']
 - cache location = /home/mnamer/.cache/mnamer-py3.9.sql
 - python version = 3.9.2
 - mnamer version = 2.4.2
 - appdirs version = 1.4.4
 - babelfish version = 0.5.5-dev
 - guessit version = 3.1.1
 - requests version = 2.25.1
 - requests cache version = 0.5.2
 - teletype version = 1.1.0

--------------------------------- stack trace ----------------------------------

Traceback (most recent call last):
  File "/home/mnamer/.local/lib/python3.9/site-packages/mnamer/__main__.py", line 23, in main
    frontend.launch()
  File "/home/mnamer/.local/lib/python3.9/site-packages/mnamer/frontends.py", line 80, in launch
    self._process_targets()
  File "/home/mnamer/.local/lib/python3.9/site-packages/mnamer/frontends.py", line 153, in _process_targets
    self._rename_and_move_file(target)
  File "/home/mnamer/.local/lib/python3.9/site-packages/mnamer/frontends.py", line 189, in _rename_and_move_file
    target.relocate()
  File "/home/mnamer/.local/lib/python3.9/site-packages/mnamer/target.py", line 242, in relocate
    destination_path.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/local/lib/python3.9/pathlib.py", line 1312, in mkdir
    self._accessor.mkdir(self, mode)
PermissionError: [Errno 13] Permission denied: '/mnt/sort'

=============================== CRASH REPORT END ===============================

Dang, it looks like mnamer crashed! Please consider filling an issue at
```

**Comment by gingerbeardman** [comment]
solution to my permissions problem: `chmod o+w` and `chmod g+w` on the folders used for destinations.

**Comment by gingerbeardman** [comment]
@jkwill87 this is not a question or a problem - it is a crash report, filed as requested in the crash report text above.

what's going on here?

**Comment by jkwill87** [comment]
> solution to my permissions problem

...

> this is not a question or a problem

...

> what's going on here?

---

You stated that you had a problem so the issue was labeled with the `question / problem` tag. You stated that you fixed your problem so it was closed.

I appreciate you sharing your crash report. If there is a feature request that I'm missing somewhere between the lines here I encourage you to elaborate and I would be happy to discuss it.

As described I don't consider this a bug. Moving and renaming files presupposes that you have read+write permissions for the source file, execute permissions for the source directory, and write permissions for the destination directory. I recognize that there may be an opportunity for mnamer to skip over files that it cannot move gracefully. ​I'm not inclined to change file or directory permissions, however. One of my personal tenants for application development is to err on the side of not doing the right thing rather than possibly doing the wrong thing-- users may not expect or intend for the permissions for their directories to change when moving files within them.

**Comment by gingerbeardman** [comment]
I would expect this issue to be closed if the crash has been solved with a change or fix to the code, or if the crash has been proven to be invalid.

As it is I can reproduce this crash on demand.

> My note about permissions was unrelated, I've now removed that comment.

Perhaps related #177
