### ISSUE TITLE
Change default TV source DB.

### ISSUE THREAD

**Issue by geekm0nkey** [jkwill87/mnamer#185]
I know there is a CLI option to change it, but is there a way to set this as a default other than specifying it at run time or changing an alias? I ask, because I have noticed that the default "tvmaze" is notorious for getting episode names out of order. As an example see Love, Death and Robots.. 

three robots 
beyond the aquila rift
ice age
sonnie's edge

should be...

sonnie's edge 
three robots 	
the witness 
suits

I know this is no fault of your app, wonderful I might add, but may consider changing the TV source default to the TVDB one.

**Comment by jkwill87** [comment]
TVDb has been threatening to drop support for their v3 API for a while now which is why TVMaze is currently the default episode provider. 

As an alternative to setting CLI flags it may be more convenient to use a config file to replace TVDb as your default, e.g. by saving `{"episode_api": "tvdb"}` in `~/.mnamer-v2.json`.
