### ISSUE TITLE
media renames should ignore '/' in episode title

### ISSUE THREAD

**Issue by 2bjc466** [jkwill87/mnamer#69]
Thank you for the quick explanation/fix for the previous two issues I opened!

Another bug or feature I'm not understanding: an episode with a '/' in the title will cause the media file to move into a subdirectory:

% mnamer --batch --episode-api=tvmaze --episode-format='{series} S{season:02}E{episode:02} - {title}{extension}' --test The\ Outsider\ S01E10.mkv 
Starting mnamer
testing mode

Processing Episode "The Outsider S01E10.mkv" (2.57GB)
moving to /.../The Outsider S01E10 - Must/can'T.mkv

1 out of 1 files processed successfully

If the default behavior is to allow any character in a media file name, there should be a way to substitute '/' (':' for macOS) in renames.

**Comment by jkwill87** [comment]
> Another bug or feature I'm not understanding: an episode with a '/' in the title will cause the media file to move into a subdirectory

Yea, this is intended to be a feature but is manifesting as a bug. mnamer attempts to construct the destination path as a string using the current working directory or specified destination directory along with the templated metadata. If that destination includes nested directories, e.g. slashes within that string, then mnamer will create them for you.
 
> If the default behavior is to allow any character in a media file name, there should be a way to substitute '/'

The problem is, as you pointed out, that slashes in the metadata fields used for templating need to be substituted out. I'll probably go with a dash though for compatibilities sake with Windows. This should be an easy enough fix.

I appreciate your help pointing out these edge cases!
