### ISSUE TITLE
Music support

### ISSUE THREAD

**Issue by digiou** [jkwill87/mnamer#72]
Hello,

currently the project supports TV series and movies. Is there any plan for music files? 

I've been looking at Plex's default metadata providers, they use Last.fm but any alternative would be nice. Plex separates artist data and album data. For more, [here](https://support.plex.tv/articles/200241558-agents/). They also try to use file-embedded metadata.

Ideally, I could (slowly) help with such functionality.

**Comment by jkwill87** [comment]
﻿It would certainly be possible. Currently mnamer’s metadata parser is built upon guessit which only supports video files. To expand further upon this and support other media types like music, ebooks, podcasts, etc. would require a more robust solution. This is something I’ve considered developing as a first step as an alternative to maintaining a sort of hodge-podge patchwork of dependencies. This is still in the ideation phase though.

In the meantime I plan to open up mnamer to other media types more immediately related to what it currently supports like subtitle files. Music support will be a little further out.

**Comment by digiou** [comment]
Hello again @jkwill87 ,

I guess the idea is to have a generic structure for the parser and apply specific strategies for the type of files later, correct? Is there any work on that already, that I could take some examples from?

Btw, after taking a quick look on what other people do, the usual strategies are:

- complete the incomplete metadata, from various sources (Spotify, MusicBrainz, etc).
- metadata + filename guess
- extract audio fingerprint and use a service (what the lib [beets](https://beets.readthedocs.io/en/stable/plugins/chroma.html) does).

I guess the easiest strategy as a start would be the tag-based one, plus filenames.

**Comment by jkwill87** [comment]
> I guess the idea is to have a generic structure for the parser and apply specific strategies for the type of files later

Currently, mnamer uses guessit to parse filename metadata and uses that to search for results from providers like tvdb, tvmaze, tmdb, and omdb to fill in what is missing. guessit does not support music files. So generally and hypothetically speaking in order to support music files mnamer would need to have a file parser for music filenames and then API provider integration for whichever service supports audio files (points one and two).

Just to take a step back to focus on the point of your earlier question--

> I've been looking at Plex's default metadata providers, they use Last.fm but any alternative would be nice

Supposing that mnamer had music support, which is not planned anytime in the immediate future, it would still not be suitable as a Plex metadata media provider. Plex already has support for TVDB and TMDB, so on the video front it wouldn't be adding anything that isn't already available.

Either way, given that the focus for mnamer 3 is subtitle and internationalization support, In my view we are at least a major version and year away from the point where music support is on the roadmap for this project. If you are keen to write a music metadata provider I'm not looking to dissuade you, in fact I wish you all the best, however this is not something that I see being aligned with the goals of this project at this time.
