### ISSUE TITLE
move json file to .config

### ISSUE THREAD

**Issue by Monirzadeh** [jkwill87/mnamer#84]
Please move .json file to .config for a cleaner home directory
i explain why in [this issue](https://github.com/dbr/tvnamer/issues/166#issue-529351822)

**Comment by jkwill87** [comment]
In the next version of mnamer you will be able to specify the config file path. In the meantime you are able to move the config file to your download directory (or whichever current working directory mnamer is called from).

**Comment by Monirzadeh** [comment]
thanks 
so i should set alias for that.
do you think default `~/.config/mnamer/` can be a better choice?

**Comment by jkwill87** [comment]
> so i should set alias for that

Sure, that or just move it to wherever you run mnamer from.

> do you think default ~/.config/mnamer/ can be a better choice?

Maybe but not necessarily in all cases. Windows, for instance, typically store this sort of file in `$HOME\AppData\Local`. Instead of adding a bunch of OS specific logic I just defaulted to the user's home directory for a start. Since I'm already using `appdirs` I can probably use that to identify the user's config directory though. Either way, in the next version of mnamer you can put it wherever you'd prefer.

**Comment by Monirzadeh** [comment]
> In the next version of mnamer you will be able to specify the config file path. In the meantime you are able to move the config file to your download directory (or whichever current working directory mnamer is called from).
> […](#)
> On May 14, 2020, at 6:38 PM, Monirzadeh ***@***.***> wrote: ﻿ Please move .json file to .config for a cleaner home directory — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

hi is it possible to set config file for mnamer as an argument now?
something like this
```
mnamer --config 
```
