### ISSUE TITLE
support for .sub/.idx subtitle files

### ISSUE THREAD

**Issue by seppi91** [jkwill87/mnamer#99]
When I've tried this tool I faced some issues with archives containing more than one subtitle file.

Example:
```
/movie.rar
- movie.mkv
- subs/
  - movie.sub
  - movie.idx
  - movie-eng.sub
  - movie-eng.idx
  - movie-forced.sub
  - movie-forced.idx
```

These Subtitles are in [VobSUB](https://wiki.multimedia.cx/index.php?title=VOBsub) format, where always a pair of sub/idx file describes a subtitle entity.

As I'm only interested in the "-forced" subtitles I've tried to add `["-forced.sub", "-forced.idx"]` into my configuration, but had no luck as we are using a suffix-match here: https://github.com/jkwill87/mnamer/blob/e79f3387e91cb7da5a9a6c23854a7f6c1e9125a0/mnamer/utils.py#L132

Probably the best thing we could do here would be to parse the `idx` fileames and looking for iso language-codes + 'forced' keyword and append them to to the new filename.

plz share your thoughts :-)

P.S. Thank you for this great utility :+1:

**Comment by jojo141185** [comment]
Hi Jessy, thanks for this great tool.
The problem seppi91 describes seems to be not completely fixed by the commit [42c4b21](https://github.com/jkwill87/mnamer/commit/42c4b21dfb67f93cdb1b043be5c1a18ba024004b). The subtitles are not yet distinguished if they are forced or unforced. Usually both variants exist for one language. 
You would have to treat the forced subtitles as a separate type by appending the term "forced" to the file name in addition to the language code.

**Comment by seppi91** [comment]
@jkwill87 Jojo141185 got a good point here. While the forced subtitle files are properly recognized and also correctly detect the appropriate language code, the "forced" suffix is not respected.

This leads to an issue when forced and a non-forced subtitle files are provided within one directory. Could we maybe add `kind_sub` as a new property (type str) to the metadata dataclass and set it to "forced" or "" depending on what has been detected

**Comment by jojo141185** [comment]
@seppi91 I think we need to open a new issue to discuss the existing problem regarding the differentiation of "forced" and "non-forced" subtitles with jkwill87.
